spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/batch
      username: sa
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
